# Generated by Django 4.2.27 on 2026-01-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_user_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="include_in_streaks",
            field=models.BooleanField(
                default=True,
                help_text="Include this user in streak tracking and perfect week calculations?",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "eligible_for_points", "include_in_streaks"],
                name="users_is_acti_ca289f_idx",
            ),
        ),
    ]
