# Generated by Django 6.0.1 on 2026-01-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_user_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="eligible_for_streaks",
            field=models.BooleanField(
                default=True,
                help_text="Is this user eligible for streaks? (If False, hidden from streak pages and ignored in group calculations)",
            ),
        ),
    ]
