# Generated by Django 4.2.27 on 2025-12-05 19:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("chores_created", models.IntegerField(default=0)),
                ("chores_marked_overdue", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("error_details", models.TextField(blank=True)),
                (
                    "execution_time_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "db_table": "evaluation_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Streak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_perfect_week", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "streaks",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_to_dollar_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0100"),
                        help_text="How many points equal one dollar (default: 0.01 = 100 points = $1)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001")),
                            django.core.validators.MaxValueValidator(Decimal("9.9999")),
                        ],
                    ),
                ),
                (
                    "max_claims_per_day",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of chores a user can claim per day",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "undo_time_limit_hours",
                    models.IntegerField(
                        default=24,
                        help_text="How many hours after completion can it be undone (default: 24)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "weekly_reset_undo_hours",
                    models.IntegerField(
                        default=24,
                        help_text="How many hours after weekly reset can it be undone (default: 24)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                ("enable_notifications", models.BooleanField(default=True)),
                (
                    "home_assistant_webhook_url",
                    models.URLField(blank=True, max_length=500),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Settings",
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="ChoreInstanceArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_id",
                    models.IntegerField(help_text="Original ChoreInstance ID"),
                ),
                ("chore_name", models.CharField(max_length=255)),
                ("assigned_to_username", models.CharField(blank=True, max_length=150)),
                ("status", models.CharField(max_length=20)),
                ("points_value", models.DecimalField(decimal_places=2, max_digits=5)),
                ("due_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("was_late", models.BooleanField(default=False)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("data_json", models.JSONField(help_text="Full original data as JSON")),
            ],
            options={
                "db_table": "chore_instance_archive",
                "ordering": ["-due_at"],
                "indexes": [
                    models.Index(
                        fields=["-due_at"], name="chore_insta_due_at_97d52f_idx"
                    ),
                    models.Index(
                        fields=["chore_name"], name="chore_insta_chore_n_de9e1e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_ending", models.DateField()),
                (
                    "points_earned",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "cash_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("converted", models.BooleanField(default=False)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("conversion_undone", models.BooleanField(default=False)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                ("perfect_week", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "converted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weekly_snapshots",
                "ordering": ["-week_ending", "user"],
                "indexes": [
                    models.Index(
                        fields=["week_ending", "converted"],
                        name="weekly_snap_week_en_b42735_idx",
                    ),
                    models.Index(
                        fields=["user", "-week_ending"],
                        name="weekly_snap_user_id_7e46fc_idx",
                    ),
                ],
                "unique_together": {("user", "week_ending")},
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("claim", "User claimed chore"),
                            ("complete", "User completed chore"),
                            ("undo", "Admin undid completion"),
                            ("force_assign", "System force-assigned chore"),
                            ("manual_assign", "Admin manually assigned chore"),
                            ("weekly_reset", "Admin performed weekly reset"),
                            ("undo_reset", "Admin undid weekly reset"),
                            ("settings_change", "Admin changed settings"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional context as JSON", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user affected by this action (if different from performer)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "action_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="action_logs_created_c06009_idx"
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="action_logs_action__ca38cc_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="action_logs_user_id_9ed3fe_idx",
                    ),
                ],
            },
        ),
    ]
