# Generated by Django 4.2.27 on 2025-12-05 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0002_choreinstance_completion_pointsledger_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RotationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_completed_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_states",
                        to="chores.chore",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rotation_states",
                "ordering": ["chore", "last_completed_date"],
                "indexes": [
                    models.Index(
                        fields=["chore", "last_completed_date"],
                        name="rotation_st_chore_i_ac36f1_idx",
                    )
                ],
                "unique_together": {("chore", "user")},
            },
        ),
    ]
