# Generated by Django 4.2.27 on 2025-12-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_skip_unskip_admin_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("claim", "User claimed chore"),
                    ("complete", "User completed chore"),
                    ("undo", "Admin undid completion"),
                    ("force_assign", "System force-assigned chore"),
                    ("manual_assign", "Admin manually assigned chore"),
                    ("weekly_reset", "Admin performed weekly reset"),
                    ("undo_reset", "Admin undid weekly reset"),
                    ("settings_change", "Admin changed settings"),
                    ("skip", "Admin skipped chore"),
                    ("unskip", "Admin unskipped chore"),
                    ("reschedule", "Admin rescheduled chore"),
                    ("clear_reschedule", "Admin cleared reschedule"),
                    ("admin", "Admin action"),
                ],
                max_length=30,
            ),
        ),
    ]
