# Generated by Django 4.2.27 on 2025-12-08 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_unclaim_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="arcade_submission_redirect_seconds",
            field=models.IntegerField(
                default=5,
                help_text="Seconds to show 'Submitted for judging' message before redirecting (default: 5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
