# Generated by Django 4.2.27 on 2025-12-05 18:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("999.99")),
                        ],
                    ),
                ),
                ("is_pool", models.BooleanField(default=True)),
                ("is_difficult", models.BooleanField(default=False)),
                ("is_undesirable", models.BooleanField(default=False)),
                ("is_late_chore", models.BooleanField(default=False)),
                ("distribution_time", models.TimeField(default="17:30")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("every_n_days", "Every N Days"),
                            ("cron", "Cron"),
                            ("rrule", "RRULE"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("n_days", models.IntegerField(blank=True, null=True)),
                ("every_n_start_date", models.DateField(blank=True, null=True)),
                ("shift_on_late_completion", models.BooleanField(default=True)),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                ("cron_expr", models.CharField(blank=True, max_length=100)),
                ("rrule_json", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_chores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChoreEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligible_users",
                        to="chores.chore",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chore_eligibility",
                "unique_together": {("chore", "user")},
            },
        ),
        migrations.CreateModel(
            name="ChoreDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offset_hours", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_as_child",
                        to="chores.chore",
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies_as_parent",
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "db_table": "chore_dependencies",
                "unique_together": {("chore", "depends_on")},
            },
        ),
    ]
