# Generated by Django 4.2.27 on 2025-12-05 19:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoreInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pool", "Pool"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                        ],
                        default="pool",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("claimed", "User claimed"),
                            ("force_assigned", "Force assigned by system"),
                            ("manual_assign", "Manually assigned by admin"),
                            ("no_eligible_users", "No eligible users"),
                            (
                                "all_completed_yesterday",
                                "All eligible users completed yesterday",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "points_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("999.99")),
                        ],
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("distribution_at", models.DateTimeField()),
                ("is_overdue", models.BooleanField(default=False)),
                ("is_late_completion", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "db_table": "chore_instances",
                "ordering": ["due_at", "chore__name"],
            },
        ),
        migrations.CreateModel(
            name="Completion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("was_late", models.BooleanField(default=False)),
                ("is_undone", models.BooleanField(default=False)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chore_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion",
                        to="chores.choreinstance",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undone_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "completions",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="PointsLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("completion", "Chore Completion"),
                            ("undo", "Undo Completion"),
                            ("weekly_reset", "Weekly Reset"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "points_change",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive for earning, negative for deduction",
                        max_digits=7,
                    ),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="chores.completion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weekly_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.weeklysnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "points_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="points_ledg_user_id_ef075d_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-created_at"],
                        name="points_ledg_transac_4a2c93_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompletionShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_awarded",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("99999.99")
                            ),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="chores.completion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "completion_shares",
                "ordering": ["-points_awarded"],
                "unique_together": {("completion", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="choreinstance",
            index=models.Index(
                fields=["status", "due_at"], name="chore_insta_status_2f2d65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="choreinstance",
            index=models.Index(
                fields=["assigned_to", "status"], name="chore_insta_assigne_ffcebc_idx"
            ),
        ),
    ]
