# Generated by Django 4.2.27 on 2025-12-06 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chores", "0003_add_parent_completion_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="choreinstance",
            name="skip_reason",
            field=models.TextField(
                blank=True, help_text="Reason for skipping this chore", null=True
            ),
        ),
        migrations.AddField(
            model_name="choreinstance",
            name="skipped_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When this chore was skipped",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="choreinstance",
            name="skipped_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who skipped this chore",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skipped_chores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="choreinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pool", "Pool"),
                    ("assigned", "Assigned"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="pool",
                max_length=20,
            ),
        ),
    ]
