# Generated by Django 4.2.27 on 2025-12-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chores", "0004_add_skip_functionality"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="reschedule_reason",
            field=models.CharField(
                blank=True, help_text="Why was this chore rescheduled", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="chore",
            name="rescheduled_at",
            field=models.DateTimeField(
                blank=True, help_text="When was this chore rescheduled", null=True
            ),
        ),
        migrations.AddField(
            model_name="chore",
            name="rescheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_chores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chore",
            name="rescheduled_date",
            field=models.DateField(
                blank=True,
                help_text="Next date this chore should appear (overrides normal schedule)",
                null=True,
            ),
        ),
    ]
