# Generated by Django 4.2.27 on 2025-12-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0005_add_reschedule_fields"),
    ]

    operations = [
        # Add default value for assignment_reason to allow empty strings
        migrations.RunSQL(
            sql="""
                CREATE TABLE chore_instances_new (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    status VARCHAR(20) NOT NULL,
                    assignment_reason VARCHAR(50) DEFAULT '' NOT NULL,
                    points_value DECIMAL NOT NULL,
                    due_at DATETIME NOT NULL,
                    distribution_at DATETIME NOT NULL,
                    is_overdue BOOL NOT NULL,
                    is_late_completion BOOL NOT NULL,
                    created_at DATETIME NOT NULL,
                    assigned_at DATETIME,
                    completed_at DATETIME,
                    updated_at DATETIME NOT NULL,
                    assigned_to_id BIGINT REFERENCES users (id),
                    chore_id BIGINT NOT NULL REFERENCES chores (id),
                    skip_reason TEXT,
                    skipped_at DATETIME,
                    skipped_by_id BIGINT REFERENCES users (id)
                );

                INSERT INTO chore_instances_new
                SELECT id, status, COALESCE(assignment_reason, ''), points_value, due_at,
                       distribution_at, is_overdue, is_late_completion, created_at,
                       assigned_at, completed_at, updated_at, assigned_to_id, chore_id,
                       skip_reason, skipped_at, skipped_by_id
                FROM chore_instances;

                DROP TABLE chore_instances;
                ALTER TABLE chore_instances_new RENAME TO chore_instances;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
