# Generated by Django 4.2.27 on 2025-12-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0006_fix_assignment_reason_null"),
    ]

    operations = [
        # Add default values for text fields to allow empty strings
        migrations.RunSQL(
            sql="""
                CREATE TABLE chores_new (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name VARCHAR(255) NOT NULL,
                    description TEXT DEFAULT '' NOT NULL,
                    points DECIMAL NOT NULL,
                    is_pool BOOL NOT NULL,
                    is_difficult BOOL NOT NULL,
                    is_undesirable BOOL NOT NULL,
                    is_late_chore BOOL NOT NULL,
                    distribution_time TIME NOT NULL,
                    schedule_type VARCHAR(20) NOT NULL,
                    n_days INTEGER,
                    every_n_start_date DATE,
                    shift_on_late_completion BOOL NOT NULL,
                    weekday INTEGER,
                    cron_expr VARCHAR(100) DEFAULT '' NOT NULL,
                    rrule_json TEXT,
                    is_active BOOL NOT NULL,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL,
                    assigned_to_id BIGINT REFERENCES users (id),
                    reschedule_reason VARCHAR(255) DEFAULT '' NOT NULL,
                    rescheduled_at DATETIME,
                    rescheduled_by_id BIGINT REFERENCES users (id),
                    rescheduled_date DATE
                );

                INSERT INTO chores_new
                SELECT id, name, COALESCE(description, ''), points, is_pool,
                       is_difficult, is_undesirable, is_late_chore, distribution_time,
                       schedule_type, n_days, every_n_start_date, shift_on_late_completion,
                       weekday, COALESCE(cron_expr, ''), rrule_json, is_active,
                       created_at, updated_at, assigned_to_id, COALESCE(reschedule_reason, ''),
                       rescheduled_at, rescheduled_by_id, rescheduled_date
                FROM chores;

                DROP TABLE chores;
                ALTER TABLE chores_new RENAME TO chores;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
