# Generated by Django 4.2.27 on 2025-12-07 05:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chores", "0007_fix_chore_text_fields_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chore",
            name="cron_expr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="chore",
            name="description",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="chore",
            name="reschedule_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why was this chore rescheduled",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ChoreTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("999.99")),
                        ],
                    ),
                ),
                ("is_pool", models.BooleanField(default=True)),
                ("is_difficult", models.BooleanField(default=False)),
                ("is_undesirable", models.BooleanField(default=False)),
                ("is_late_chore", models.BooleanField(default=False)),
                ("distribution_time", models.TimeField(default="17:30")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("every_n_days", "Every N Days"),
                            ("cron", "Cron"),
                            ("rrule", "RRULE"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("n_days", models.IntegerField(blank=True, null=True)),
                ("every_n_start_date", models.DateField(blank=True, null=True)),
                ("shift_on_late_completion", models.BooleanField(default=True)),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                ("cron_expr", models.CharField(blank=True, default="", max_length=100)),
                ("rrule_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chore_templates",
                "ordering": ["template_name"],
            },
        ),
    ]
