# Generated by Django 4.2.27 on 2025-12-07 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chores", "0008_alter_chore_cron_expr_alter_chore_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArcadeCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_time_seconds", models.IntegerField()),
                ("approved", models.BooleanField(default=True)),
                ("judge_notes", models.TextField(blank=True, default="")),
                ("base_points", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "bonus_points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_points", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_high_score", models.BooleanField(default=False)),
                ("rank_at_completion", models.IntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "arcade_completions",
                "ordering": ["completion_time_seconds"],
            },
        ),
        migrations.CreateModel(
            name="ArcadeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("elapsed_seconds", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stopped", "Stopped - Awaiting Approval"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("cumulative_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcade_sessions",
                        to="chores.chore",
                    ),
                ),
                (
                    "chore_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcade_sessions",
                        to="chores.choreinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arcade_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "arcade_sessions",
            },
        ),
        migrations.CreateModel(
            name="ArcadeHighScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_seconds", models.IntegerField()),
                (
                    "rank",
                    models.IntegerField(
                        choices=[(1, "1st Place"), (2, "2nd Place"), (3, "3rd Place")]
                    ),
                ),
                ("achieved_at", models.DateTimeField()),
                (
                    "arcade_completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_score_entry",
                        to="chores.arcadecompletion",
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_scores",
                        to="chores.chore",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="high_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "arcade_high_scores",
                "ordering": ["chore", "rank"],
            },
        ),
        migrations.AddField(
            model_name="arcadecompletion",
            name="arcade_session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completion",
                to="chores.arcadesession",
            ),
        ),
        migrations.AddField(
            model_name="arcadecompletion",
            name="chore",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arcade_completions",
                to="chores.chore",
            ),
        ),
        migrations.AddField(
            model_name="arcadecompletion",
            name="chore_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arcade_completion",
                to="chores.choreinstance",
            ),
        ),
        migrations.AddField(
            model_name="arcadecompletion",
            name="judge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="judged_arcades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="arcadecompletion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arcade_completions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="arcadesession",
            index=models.Index(
                fields=["user", "is_active"], name="arcade_sess_user_id_81926d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arcadesession",
            index=models.Index(fields=["status"], name="arcade_sess_status_e23ae3_idx"),
        ),
        migrations.AddIndex(
            model_name="arcadesession",
            index=models.Index(fields=["chore"], name="arcade_sess_chore_i_3c07f0_idx"),
        ),
        migrations.AddIndex(
            model_name="arcadehighscore",
            index=models.Index(
                fields=["chore", "rank"], name="arcade_high_chore_i_3a93b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arcadehighscore",
            index=models.Index(fields=["user"], name="arcade_high_user_id_b5edf8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="arcadehighscore",
            unique_together={("chore", "rank")},
        ),
        migrations.AddIndex(
            model_name="arcadecompletion",
            index=models.Index(
                fields=["user", "chore"], name="arcade_comp_user_id_c2eedc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arcadecompletion",
            index=models.Index(
                fields=["chore", "completion_time_seconds"],
                name="arcade_comp_chore_i_8cf224_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arcadecompletion",
            index=models.Index(
                fields=["is_high_score"], name="arcade_comp_is_high_44225d_idx"
            ),
        ),
    ]
