# Generated by Django 4.2.27 on 2025-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0011_add_piano_score_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="complete_later",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this chore can be completed later in the day (e.g., after dinner). Unchecked means it should be completed immediately.",
            ),
        ),
        migrations.AddField(
            model_name="choretemplate",
            name="complete_later",
            field=models.BooleanField(default=False),
        ),
    ]
