# Generated by Django 4.2.27 on 2025-12-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0012_add_complete_later_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="choreinstance",
            index=models.Index(
                fields=["chore", "status"], name="chore_inst_chore_status_idx"
            ),
        ),
    ]
