# Generated by Django 4.2.27 on 2026-01-05 17:53

from decimal import Decimal
from django.db import migrations, models


def populate_bonus_percentage(apps, schema_editor):
    """Calculate bonus_percentage from existing bonus_points and base_points."""
    ArcadeCompletion = apps.get_model("chores", "ArcadeCompletion")

    for completion in ArcadeCompletion.objects.all():
        if completion.base_points > 0 and completion.bonus_points > 0:
            # Calculate percentage: bonus_points / base_points
            completion.bonus_percentage = (completion.bonus_points / completion.base_points)
        else:
            completion.bonus_percentage = Decimal('0.00')
        completion.save(update_fields=['bonus_percentage'])


def reverse_populate_bonus_percentage(apps, schema_editor):
    """Reverse migration - set all bonus_percentage to 0."""
    ArcadeCompletion = apps.get_model("chores", "ArcadeCompletion")
    ArcadeCompletion.objects.all().update(bonus_percentage=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0013_add_chore_status_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcadecompletion",
            name="bonus_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Bonus percentage applied at approval time (0.00, 0.25, or 0.50)",
                max_digits=5,
            ),
        ),
        migrations.RunPython(populate_bonus_percentage, reverse_populate_bonus_percentage),
    ]
