# Generated by Django 4.2.27 on 2025-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0013_add_chore_status_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreinstance',
            name='assignment_reason',
            field=models.CharField(blank=True, choices=[('claimed', 'User claimed'), ('force_assigned', 'Force assigned by system'), ('manual_assign', 'Manually assigned by admin'), ('fixed', 'Fixed assignment'), ('no_eligible_users', 'No eligible users'), ('all_completed_yesterday', 'All eligible users completed yesterday'), ('parent_completion', 'Spawned from parent chore completion')], max_length=50),
        ),
    ]
