# Generated by Django 4.2.27 on 2026-01-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0016_add_bonus_percentage_to_arcade_completion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arcadehighscore",
            options={"ordering": ["chore", "time_seconds"]},
        ),
        migrations.RemoveIndex(
            model_name="arcadehighscore",
            name="arcade_high_chore_i_3a93b6_idx",
        ),
        migrations.AlterUniqueTogether(
            name="arcadehighscore",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="arcadehighscore",
            index=models.Index(
                fields=["chore", "time_seconds"], name="arcade_high_chore_i_dea494_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="arcadehighscore",
            name="rank",
        ),
    ]
