# Generated by Django 4.2.27 on 2025-12-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_label",
                    models.CharField(
                        default="points",
                        help_text='The label to use for points throughout the site (e.g., "points", "stars", "coins")',
                        max_length=50,
                    ),
                ),
                (
                    "points_label_short",
                    models.CharField(
                        default="pts",
                        help_text='Short version of the points label (e.g., "pts", "★", "coins")',
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
